// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzzMYE-mYDFFVazm7auozEmoGwy0f__w',
    appId: '1:986483129929:web:b7a9194b3f68458f9ec998',
    messagingSenderId: '986483129929',
    projectId: 'dailynews-84762',
    authDomain: 'dailynews-84762.firebaseapp.com',
    storageBucket: 'dailynews-84762.firebasestorage.app',
    measurementId: 'G-G7EKJH1CT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkIa80h0oxRjlvM5ENwBXZboxrSR-h75M',
    appId: '1:986483129929:android:2322abaa020038ca9ec998',
    messagingSenderId: '986483129929',
    projectId: 'dailynews-84762',
    storageBucket: 'dailynews-84762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPNTjZcoZbaZQHAcamfzbl5j76R-MWyo',
    appId: '1:986483129929:ios:fbde82e09bc833d59ec998',
    messagingSenderId: '986483129929',
    projectId: 'dailynews-84762',
    storageBucket: 'dailynews-84762.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPNTjZcoZbaZQHAcamfzbl5j76R-MWyo',
    appId: '1:986483129929:ios:fbde82e09bc833d59ec998',
    messagingSenderId: '986483129929',
    projectId: 'dailynews-84762',
    storageBucket: 'dailynews-84762.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVzzMYE-mYDFFVazm7auozEmoGwy0f__w',
    appId: '1:986483129929:web:055e98df58426d879ec998',
    messagingSenderId: '986483129929',
    projectId: 'dailynews-84762',
    authDomain: 'dailynews-84762.firebaseapp.com',
    storageBucket: 'dailynews-84762.firebasestorage.app',
    measurementId: 'G-N1ZYP83PBX',
  );
}
